### ISSUE TITLE
Update in v4.0.0

### ISSUE THREAD

**Issue by blivesta** [blivesta/animsition#50]
#49 #46 #45 #44 #34 #33

## ToDo
* [ ] ~~Remove of event `$(window).load`.~~
* [ ] ~~Remove of `options.overlay`.~~
* [ ] ~~Inclusion of options `inDelay` and `outDelay`.~~
* [x] Change of unit for time from `s` to `ms`.
* [x] Change and addition of event API.
* [x] Update of `loading` options.
* [x] Remove of `.less` and `.scss` in the `src` folder, with plan to shift to `css`.
* [x] Plan to shift from `grunt` to `gulp` or `node` (npm script).
* [x] Addition of transition options
* [x] Addition of timeout options

## Demo files
~~https://gist.github.com/blivesta/b1a01c2a4d39bf1ea628/~~
~~https://gist.github.com/blivesta/b1a01c2a4d39bf1ea628/download~~

js https://github.com/blivesta/animsition/blob/v4.0.0/dist/js/jquery.animsition.js
css https://github.com/blivesta/animsition/blob/v4.0.0/dist/css/animsition.css
html(example) https://gist.github.com/blivesta/6f7a51440f3b9ec283d

**Comment by nvartolomei** [comment]
What is use case for this code in v4.0.0:

```
  // last callback
  if (methods.counts.in.length === methods.counts.out.length) {
  $this.trigger('animsition.outDone');

  return options.transition(url);
}
```

**Comment by nvartolomei** [comment]
Can't understand what's the point for counting inits, ins and outs functions calls, can you explain a little bit?

**Comment by nvartolomei** [comment]
And the only way to trigger transitions now is programmatically?

The plugin description says `A simple and easy jQuery plugin for css animated page transitions.` and now you are moving into another direction :(

Regarding the Ajax example, it is not correct, the out transition will not work on dynamically loaded element, also click events for links inside them are still not handled.

**Comment by blivesta** [comment]
https://github.com/blivesta/animsition/blob/v4.0.0/dist/js/jquery.animsition.js#L218

In the first place, this update aims to call methods by catching external events. 
I too realized the discrepancy between the project concept and the actual program as I was making changes.  But I didn’t stop it because I was drunk... 
As for `$ajax`, I think it is as you pointed out.  It would not be effective to dynamically load the elements. 
But it is not for me to decide if we should change this in the plug-in, and I also do not have the time to do this now. 
As this is not the master branch, it is not necessary to forcibly update this. 
If anyone has any good ideas, it would greatly help if you can commit them. 


## v4.0.0-alpha.1
js
https://github.com/blivesta/animsition/blob/v4.0.0/dist/js/jquery.animsition.js

css
https://github.com/blivesta/animsition/blob/v4.0.0/dist/css/animsition.css

html
https://gist.github.com/blivesta/6f7a51440f3b9ec283d

**Comment by nvartolomei** [comment]
@blivesta my main concern now is ajax, I have a animsition container, inside I use infinite scroll which dynamically adds elements inside container, animation for this I handle myself via css and masonry. Now all links that are dynamically loaded do not have click event handlers, because you attach them on animsition initialization.

It is this line: `$(options.linkElement).on('click.' + namespace, function(event) {`

AFAIK there are 2 solutions to this problem, move binding of click handlers in a separate method which can be called like animsition('in'), which will bind click handlers on new elements. Now this method can be implemented in many ways, I'm not sure which one is better.

The second solution would be to use delegation, http://api.jquery.com/delegate/, see examples for dynamically added items.

Later I will add an example for this.

Please read this when you will not be drunk.

More to come,
Nicolae :)

**Comment by gauravpadia** [comment]
@blivesta @nvartolomei The issue event not applying to dynamically loaded links I think can easily be fixed by changing this statement ```$(options.linkElement).on('click.' + namespace, function(event) {``` to ```$('body').on('click', options.linkElement, function(event) {```

Thanks.

**Comment by nvartolomei** [comment]
@gauravpadia, this is what I talked about, although I'd attach handler to animsition element so only links inside it will be handled.

Tomorrow I will come with a proposal let's see if we can agree on something :yum:

**Comment by blivesta** [comment]
I have not fully checked it, but using `$.ajax` in this manner could be effective for dynamically loaded elements as well, even it that might be forceful.
However, I think that loader does not work and the code require brushup. :beers:
https://gist.github.com/blivesta/6f7a51440f3b9ec283de#file-dynamic-html-L20-L68

#44 #46

**Comment by blivesta** [comment]
> The second solution would be to use delegation, http://api.jquery.com/delegate/, see examples for dynamically added items.

As of jQuery 1.7, `.delegate()` has been superseded by the `.on()` method. 

@nvartolomei I will wait for your example.:yum:
@gauravpadia :+1:

**Comment by blivesta** [comment]
5724b392bf1195950a039c3e2236a01e2cf5a029
